### ISSUE TITLE
install.ps1 fails

### ISSUE THREAD

**Issue by thommay** [chef/omnitruck#135] opened 2015-10-06 11:22 UTC
Installing using the instructions in the 0.9 preview blog post. Windows 10, PS 4. 

```
PS C:\Users\thom> . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chefdk

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}
Installing chefdk from C:\Users\thom\AppData\Local\Temp\chefdk-0.8.0%2B20150930085008-1-x86.msi
msiexec was not successful. Received exit code 1603
At line:246 char:9
+         throw "msiexec was not successful. Received exit code $($p.Ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1603:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1603
```

running `msiexec.exe /i  C:\Users\thom\AppData\Local\Temp\chefdk-0.8.0%2B20150930085008-1-x86.msi` manually is successful.

**Comment by alexpop** [comment] 2015-10-06 11:59
I'm getting the following error on a Windows 7 VM with Powershell 5:

```
PS C:\Users\mydesktop> . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chefdk

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}
Installing chefdk from C:\Users\MYDESK~1\AppData\Local\Temp\chefdk-0.8.0%2B20150930085008-1-x86.msi
msiexec was not successful. Received exit code 1625
At line:246 char:9
+         throw "msiexec was not successful. Received exit code $($p.Ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1625:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1625
```

Manual installation works for me also:

```
msiexec.exe /i C:\Users\MYDESK~1\AppData\Local\Temp\chefdk-0.8.0%2B20150930085008-1-x86.msi
```

If I log to a file using this command:
```
msiexec.exe /i C:\Users\MYDESK~1\AppData\Local\Temp\chefdk-0.8.0%2B20150930085008-1-x86.msi /quiet /l*v+ install.log
```

I get this at the end of the 24MB log file:
```
Property(S): SOURCEDIR = C:\Users\MYDESK~1\AppData\Local\Temp\
Property(S): SourcedirProduct = {799EF454-3F0C-4E1C-BF9D-CEE115998CCD}
Property(S): ProductToBeRegistered = 1
MSI (s) (74:34) [12:54:38:635]: Note: 1: 1708 
MSI (s) (74:34) [12:54:38:635]: Note: 1: 2205 2:  3: Error 
MSI (s) (74:34) [12:54:38:635]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1708 
MSI (s) (74:34) [12:54:38:635]: Note: 1: 2205 2:  3: Error 
MSI (s) (74:34) [12:54:38:635]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (s) (74:34) [12:54:38:635]: Product: Chef Development Kit v0.8.0 -- Installation failed.

MSI (s) (74:34) [12:54:38:636]: Windows Installer installed the product. Product Name: Chef Development Kit v0.8.0. Product Version: 0.8.0.1. Product Language: 1033. Manufacturer: "Chef Software, Inc. <maintainers@chef.io>". Installation success or error status: 1603.

MSI (s) (74:34) [12:54:38:678]: Deferring clean up of packages/files, if any exist
MSI (s) (74:34) [12:54:38:678]: MainEngineThread is returning 1603
MSI (s) (74:18) [12:54:38:680]: RESTART MANAGER: Session closed.
MSI (s) (74:18) [12:54:38:680]: No System Restore sequence number for this installation.
=== Logging stopped: 06/10/2015  12:54:38 ===
MSI (s) (74:18) [12:54:38:681]: User policy value 'DisableRollback' is 0
MSI (s) (74:18) [12:54:38:681]: Machine policy value 'DisableRollback' is 0
MSI (s) (74:18) [12:54:38:681]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (74:18) [12:54:38:681]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (74:18) [12:54:38:681]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (74:18) [12:54:38:681]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (s) (74:18) [12:54:38:682]: Restoring environment variables
MSI (c) (B0:00) [12:54:38:721]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (B0:00) [12:54:38:721]: MainEngineThread is returning 1603
=== Verbose logging stopped: 06/10/2015  12:54:38 ===
```

**Comment by jaym** [comment] 2015-10-07 22:06
can you guys still repro. It works fine on my windows 8.1 box

**Comment by alexpop** [comment] 2015-10-09 08:58
Yes @jaym 

```
PS C:\Users\mydesktop> . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chefdk

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}
Installing chefdk from C:\Users\MYDESK~1\AppData\Local\Temp\chefdk-0.9.0%2B20151008085010-1-x86.msi
msiexec was not successful. Received exit code 1603
At line:246 char:9
+         throw "msiexec was not successful. Received exit code $($p.Ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1603:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1603

PS C:\Users\mydesktop> . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -project chefdk

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetadata, Install-Project, install}
Installing chefdk from C:\Users\MYDESK~1\AppData\Local\Temp\chefdk-0.9.0-1-x86.msi
msiexec was not successful. Received exit code 1603
At line:246 char:9
+         throw "msiexec was not successful. Received exit code $($p.Ex ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1603:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1603
```

**Comment by btm** [comment] 2016-02-04 17:22
You will get a 1603 if you run in a non-administrator powershell. To be clear, that doesn't mean that the user has to be an Administrator alone, that means when you start the powershell process itself you have to right click and "run as administrator," typically then get the UAC elevation prompt, and approve it.

**Comment by btm** [comment] 2016-02-04 19:18
I was able to reproduce this issue even when running as an Administrator. I believe it had to do with permissions on something under `\opscode\chef` (or `\opscode\chefdk`). After I deleted the directory tree manually (and maybe uninstalled via add/remove programs) I couldn't reproduce it anymore.

**Comment by robbAtEBSCO** [comment] 2017-11-21 21:11
I was running as Admin when I got the 1603.  No errors, after I deleted the opscode tree, uninstalled Chef and reran chef-client.

**Comment by jtimberman** [comment] 2018-11-26 20:08
Hello,

I'm closing this issue out due to its age and that various things have changed in the years since it was opened, and it doesn't seem there's a reliable reproduction scenario, is there? If this is still an issue affecting people, please open a new issue with complete details about the versions of Chef, Windows, PowerShell, etc.

Thank you
Joshua

**Closed by jtimberman** 2018-11-26 20:08 UTC
