### ISSUE TITLE
Downloaded metadata file is corrupted or an uncaught error

### ISSUE THREAD

**Issue by Subhranshu** [chef/omnitruck#181] opened 2016-05-20 11:33 UTC
Hi Team

I am getting this error while deploying clearwater-bono using Juju, 

I am not sure how to resolve that,

2016-05-20 11:26:18 INFO install Reading package lists...
2016-05-20 11:26:18 INFO install Building dependency tree...
2016-05-20 11:26:18 INFO install Reading state information...
2016-05-20 11:26:18 INFO install curl is already the newest version.
2016-05-20 11:26:18 INFO install git is already the newest version.
2016-05-20 11:26:18 INFO install libxml2-dev is already the newest version.
2016-05-20 11:26:18 INFO install libxslt1-dev is already the newest version.
2016-05-20 11:26:18 INFO install wget is already the newest version.
2016-05-20 11:26:18 INFO install 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
2016-05-20 11:26:18 INFO install Downloading Chef 11.6.0 for ubuntu...
2016-05-20 11:26:18 INFO install downloading https://www.opscode.com/chef/metadata?v=11.6.0&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
2016-05-20 11:26:18 INFO install   to file /tmp/install.sh.6144/metadata.txt
2016-05-20 11:26:18 INFO install trying wget...
2016-05-20 11:26:20 INFO install sha1   5fe8e4e9ddfd8ba66597670f1a1029c3409b9453
2016-05-20 11:26:20 INFO install sha256 1f7360b9cf3af4f5704f5f672c620d480b2776c4d24771ba4d4b590e388baea0
2016-05-20 11:26:20 INFO install url    https://packages.chef.io/stable/ubuntu/12.04/chef_11.6.0-1.ubuntu.12.04_amd64.deb
2016-05-20 11:26:20 INFO install version        11.6.0downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
2016-05-20 11:26:20 INFO install Version: 11.6.0
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
2016-05-20 11:26:20 INFO install Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
2016-05-20 11:26:20 INFO install More Chef support resources can be found at https://www.getchef.com/support
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install Please include as many details about the problem as possible i.e., how to reproduce
2016-05-20 11:26:20 INFO install the problem (if possible), type of the Operating System and its version, etc.,
2016-05-20 11:26:20 INFO install and any other relevant details that might help us with troubleshooting.
2016-05-20 11:26:20 INFO install
2016-05-20 11:26:20 INFO install HEAD is now at 9e0cb1c... Merge pull request #163 from Metaswitch/fix_merge

Best Regards,
Subhranshu Dwivedi

**Comment by sersut** [comment] 2016-05-20 17:02
Does this repro consistently @Subhranshu ? Looks like the md5 checks have failed when comparing it with the downloaded package.

**Comment by sersut** [comment] 2016-05-20 17:03
One thing that got changes is that now we do not have `md5` information returned from omnitruck. We make the checks using `sha256`. Maybe the mechanism you are using is still using `md5` ?

**Comment by Subhranshu** [comment] 2016-05-20 17:12
Thanks for replying Serdar,

Actually its consistently failing,

And we using sha256 only here,

As also indicated in above logs:
2016-05-20 11:26:20 INFO install sha256 

Is there anyother way to double check ? As I am struggling with this from a quite a long now and want to resolve this.

**Comment by Subhranshu** [comment] 2016-05-22 07:39
Please help as I have tried almost everything but this metadata issue is not getting resolved,

Or if there is any work around which i can do to resolve it

**Comment by sersut** [comment] 2016-05-26 17:45
Hey @Subhranshu. Sorry for the late response. 

I am not sure what "clearwater-bono using Juju" is referring to but you can check out `install.sh` which can install this version correctly:

```

**Comment by jtimberman** [comment] 2018-11-15 00:05
Hello,

I'm sorry that we never followed up on this issue! As it is quite old and there have been many changes to the products and operating systems involved, I'm going to close this issue, as reproducing it would be difficult, if not impossible.

Cheers
Joshua

**Closed by jtimberman** 2018-11-15 00:05 UTC
