### ISSUE TITLE
Oracle Linux 6.5 install of chef client fails

### ISSUE THREAD

**Issue by amyles** [chef/omnitruck#183] opened 2016-05-31 13:34 UTC
Hi 
I am trying to bootstrap an Oracle Linux 6.5 node with Chef 12. This was working back in early April but is now failing with an SSL certificate issue, the error is:

> ERROR: certificate common name `*.bintray.com' doesn't match requested host name`packages.chef.io'.

None of the flags to disable SSL cert validation seem to help here, neither --bootstrap-curl-options and/or --bootstrap-wget-options seem to have any effect. 

There are a couple of similar issues [here](https://github.com/chef/mixlib-install/issues/91) and [here](https://github.com/chef/omnitruck/issues/176) but their fixes do not seem to have solved my specific issue with Oracle Linux 6.5.

**Comment by amyles** [comment] 2016-05-31 14:34
On my chef workstation I am using :

> amyles@braan:~/chef-repo$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0

and on the Chef server:

> [root@host-48-232 ~]# head -n1 /opt/opscode/version-manifest.txt
chef-server 12.5.0

**Comment by sersut** [comment] 2016-05-31 20:25
This is an interesting case. We return ssl compatible urls for certain platforms like https://github.com/chef/mixlib-install/blob/dc9fdf068de13980a83a970f2cb2b6f4ee0b129f/lib/mixlib/install/backend/bintray.rb#L221-L226. But our magic does not work here because omnitruck does an invisible platform mapping for `Oracle Linux 6.5`. I think we have two options:

1. Make omnitruck convert the base URL when doing mapping. 
2. Move the omnitruck's platform mapping code into mixlib-install. 

I recommend to go with option 2. Thoughts @schisamo

**Comment by schisamo** [comment] 2016-05-31 20:32
@sersut I agree, we need to keep making Omnitruck as dumb as possible.

**Comment by amyles** [comment] 2016-06-01 09:02
It also seems to be an issue on FreeBSD10.

**Comment by sersut** [comment] 2016-06-01 23:06
👍 We have a plan of record but I will be away until the end of next week. After that this will be the first thing I'll look into if not fixed then 😄

**Comment by amyles** [comment] 2016-07-20 12:15
Hi @sersut and @schisamo , any news on this issue?

**Comment by ldecaro** [comment] 2016-07-26 14:03
Hi is there any updates and or planned fixes for this issue? It has been opened for a while now...

**Comment by amyles** [comment] 2016-08-10 09:52
So far I'm using the following flag on the bootstrap command:
--bootstrap-install-command="rpm -ivh http://someserver:8081/artifactory/osc-local/opscode/chef-client/12.12.15-1/chef-12.12.15-1.el6.x86_64.rpm"
after staging the rpm on a webserver. Works as a one off workaround but a proper fix would be great.

**Comment by jtimberman** [comment] 2018-11-14 23:59
Hello,

I'm sorry that we never followed up on this issue! As it is quite old and there have been many changes to the products and operating systems involved, I'm going to close this issue, as reproducing it would be difficult, if not impossible.

It's also entirely possible that this was fixed at some point.

Cheers
Joshua

**Closed** 2018-11-14 23:59 UTC
