### ISSUE TITLE
https://omnitruck.chef.io/products inconsistently returns 403

### ISSUE THREAD

**Issue by davidwrede** [chef/omnitruck#229] opened 2017-04-03 18:49 UTC
Our [Omnitruck API doc page](https://docs.chef.io/api_omnitruck.html) has a link to https://omnitruck.chef.io/products. For users, this link sometimes resolves to a 403 and other times it resolves correctly (i.e. returns a JSON list of products).

![screen shot 2017-04-03 at 11 47 27 am](https://cloud.githubusercontent.com/assets/1634752/24625326/82b728f2-1863-11e7-9a45-2db503195d72.png)

If there is a different endpoint that we should be using, let me know and I'll update the docs.

Thanks!

**Comment by wrightp** [comment] 2017-04-13 15:09
@davidwrede a new version has been deployed. Are you still experiencing this issue?

**Comment by davidwrede** [comment] 2017-04-14 00:19
Yup @wrightp. I shut down all browser instances and am able to repro the problem. Refreshing the page doesn't fix the issue.

**Comment by americanhanko** [comment] 2017-06-02 21:01
Currently experiencing this right now. However:

```shell
$ curl https://omnitruck.chef.io/products
[
  "analytics",
  "angry-omnibus-toolchain",
  "angrychef",
  "automate",
  "chef",
  "chef-backend",
  "chef-server",
  "chef-server-ha-provisioning",
  "chefdk",
  "compliance",
  "delivery",
  "ha",
  "harmony",
  "inspec",
  "manage",
  "marketplace",
  "omnibus-toolchain",
  "private-chef",
  "push-jobs-client",
  "push-jobs-server",
  "reporting",
  "supermarket",
  "sync"
]

**Comment by brewn** [comment] 2017-10-09 17:11
A user reported this again last week in community slack - I wasn't able to replicate the issue at the time, and the problem cleared up as it usually does. However I pulled up the page again this morning and received a `forbidden` error:

![forbidden](https://user-images.githubusercontent.com/21040805/31349963-4a74bdfe-acf3-11e7-8f19-fced7878ba07.png)

**Comment by wrightp** [comment] 2017-10-10 15:04
Looking into this today

**Comment by brewn** [comment] 2018-04-03 21:06
Looks like we have another report of this:
https://github.com/chef/chef-web-docs/pull/1323

**Comment by jtimberman** [comment] 2018-11-26 20:20
Hello,

This hasn't been reliably reproduced or widely reported. We're also moving the omnitruck service to new infrastructure soon. As such, I'm going to close this. We can reopen if it comes up again when we're running on the new systems.

Cheers
Joshua

**Closed by jtimberman** 2018-11-26 20:20 UTC
