### ISSUE TITLE
Installation fails on Amazon Linux 2

### ISSUE THREAD

**Issue by kbessas** [chef/omnitruck#360] opened 2018-06-27 07:52 UTC
When using packer to provision an Amazon Linux 2 AMI, getting an error. The URL that is constructed doesn't exist.

Command used:
```
curl -L https://omnitruck.chef.io/install.sh | sudo bash
```

URL:
```
https://omnitruck.chef.io/stable/chef/metadata?v=14.3.20&p=amazon linux 2&pv=amazon linux 2&m=x86_64
```

Logs:
```
1530085124,,ui,say,==> amazon-ebs: Provisioning with chef-solo
1530085124,,ui,message,    amazon-ebs: Installing Chef...
1530085124,,ui,message,    amazon-ebs:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
1530085124,,ui,message,    amazon-ebs:                                  Dload  Upload   Total   Spent    Left  Speed
1530085124,,ui,message,    amazon-ebs: 100 23429  100 23429    0     0  23429      0  0:00:01 --:--:--  0:00:01  224k
1530085124,,ui,message,    amazon-ebs: amazon linux 2 amazon linux 2 x86_64
1530085124,,ui,message,    amazon-ebs: Getting information for chef stable 14.3.20 for amazon linux 2...
1530085124,,ui,message,    amazon-ebs: downloading https://omnitruck.chef.io/stable/chef/metadata?v=14.3.20&p=amazon linux 2&pv=amazon linux 2&m=x86_64
1530085124,,ui,message,    amazon-ebs:   to file /tmp/install.sh.3236/metadata.txt
1530085124,,ui,message,    amazon-ebs: trying curl...
1530085158,,ui,message,    amazon-ebs: cat: /tmp/install.sh.3236/metadata.txt: No such file or directory
1530085158,,ui,message,    amazon-ebs:
1530085158,,ui,message,    amazon-ebs: grep: /tmp/install.sh.3236/metadata.txt: No such file or directory
1530085158,,ui,message,    amazon-ebs: downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
1530085158,,ui,message,    amazon-ebs: Version: 14.3.20
1530085158,,ui,message,    amazon-ebs:
1530085158,,ui,message,    amazon-ebs: Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
1530085158,,ui,message,    amazon-ebs: Alternatively%!(PACKER_COMMA) feel free to open a Support Ticket at https://www.chef.io/support/tickets
1530085158,,ui,message,    amazon-ebs: More Chef support resources can be found at https://www.chef.io/support
1530085158,,ui,message,    amazon-ebs:
1530085158,,ui,message,    amazon-ebs: Please include as many details about the problem as possible i.e.%!(PACKER_COMMA) how to reproduce
1530085158,,ui,message,    amazon-ebs: the problem (if possible)%!(PACKER_COMMA) type of the Operating System and its version%!(PACKER_COMMA) etc.%!(PACKER_COMMA)
1530085158,,ui,message,    amazon-ebs: and any other relevant details that might help us with troubleshooting.
1530085158,,ui,message,    amazon-ebs:
```

**Comment by zl4bv** [comment] 2018-07-02 03:18
Seeing it too on Amazon Linux 2. Seems fine on Amazon Linux 1 and other Linux flavours.

```
amazon-ebs: Installing Chef...
amazon-ebs: amazon linux 2 amazon linux 2 x86_64
amazon-ebs: Getting information for chef stable 13.4.24 for amazon linux 2...
amazon-ebs: downloading https://omnitruck.chef.io/stable/chef/metadata?v=13.4.24&p=amazon linux 2&pv=amazon linux 2&m=x86_64
amazon-ebs:   to file /tmp/install.sh.3605/metadata.txt
amazon-ebs: trying wget...
amazon-ebs: trying curl...
amazon-ebs: cat: /tmp/install.sh.3605/metadata.txt: No such file or directory
```

**Comment by siulcode** [comment] 2018-07-06 16:51
Hi there, 
do we have an eta on when is this going to be published into the install script? 

I'm still getting the corrupted error on Linux 2 for `https://omnitruck.chef.io/install.sh`

`# curl -L https://omnitruck.chef.io/install.sh | bash -s -- -P "chef" -c "stable"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23429  100 23429    0     0  23429      0  0:00:01 --:--:--  0:00:01  672k
amazon linux 2 amazon linux 2 x86_64
Getting information for chef stable  for amazon linux 2...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=amazon linux 2&pv=amazon linux 2&m=x86_64
  to file /tmp/install.sh.3542/metadata.txt
trying wget...
trying curl...
cat: /tmp/install.sh.3542/metadata.txt: No such file or directory

grep: /tmp/install.sh.3542/metadata.txt: No such file or directory
downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version: 

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.
`

Any help on this would be greatly appreciated. 
LL.

**Comment by tas50** [comment] 2018-07-06 17:00
The current fix on master fails on some platforms so we're still working to get a fix that gets amazon right while still properly detecting all the various RHEL derivatives.

**Comment by siulcode** [comment] 2018-07-09 13:02
@tas50 is there any workaround I can do in the meantime?

**Comment by ilovemysillybanana** [comment] 2018-07-09 17:38
This was working fine for me until literally two minutes ago, what could have caused it to just break like that?

**Comment by tas50** [comment] 2018-07-09 17:39
@ilovemysillybanana What version of amazon linux are you on?

**Comment by ilovemysillybanana** [comment] 2018-07-09 17:41
@tas50 
amazon 2 lts 2017.12 -x86_64

**Comment by tas50** [comment] 2018-07-09 17:45
@ilovemysillybanana That's the RC which has a very odd version string. I'm trying to work around that right now, but you're also going to want to upgrade your distro since that's not a supported Amazon Linux release now that 2.0 is out.

**Comment by ilovemysillybanana** [comment] 2018-07-09 18:08
@tas50 
Switching to amazon `Amazon Linux 2 AMI (HVM), SSD Volume Type` alleviated the issue for now. Thanks.

**Comment by tas50** [comment] 2018-07-09 18:13
I have a fix in the works that will allow the previous RC releases to correctly install as well.

**Comment by kpettijohn** [comment] 2018-08-01 23:09
Running into this issue as well for our Amazon 2 builds. I was hoping that I could override the `platform` and `platform_version` to point at `el 7.x` but the overrides don't seem to be working. 
```
platforms:
  - name: amazon2
    provisioner:
      name: chef_zero
      product: chef
      product_version: 'latest'
      channel: stable
      platform: el
      platform_version: 7.5
      architecture: x86_64
```

ChefDK details:
```
chef -v
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

**Comment by espoelstra** [comment] 2018-09-26 17:09
Interestingly it appears that the `chef-client` package correctly installed on Amazon Linux 2 but due to a missing `.service` file for `org.freedesktop.PolicyKit1` it wasn't able to perform `systemctl enable chef-client` to start on boot. Has this been reported anywhere else @tas50 ?

**Comment by tas50** [comment] 2018-12-07 03:54
I'm closing this out since we're remapping here in omnitruck and also detecting in mixlib-install. This should be entirely resolved at this point.

**Closed by tas50** 2018-12-07 03:54 UTC
Labels: bug
